app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

http.proxy:
auth:
  dir: auth
  domain: localhost:19013/api
download.dir: download

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/open_mediation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
