app:
  env: prod

logging:
  config: classpath:log4j2-prod.xml

http.proxy:
auth:
  dir: auth
  domain: xxx.xx.com
download.dir: download
admob:
  client_id: your client id
  client_secret: your client secret

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false
    username: xxx
    password: xxxxx