app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

http.proxy: 172.20.5.30:8889
auth:
  dir: auth
  domain: localhost:19013/api
download.dir: download

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.114/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false
    username: root
    password: NPN_loczzf2_root
