app:
  env: prod

logging:
  config: classpath:log4j2-prod.xml

http.proxy: 
auth:
  dir: auth
  domain: 127.0.0.1:19013
download.dir: download

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false
    username: user
    password: passswd 
